// <auto-generated />
namespace CineWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NumberAvailableAddedToMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberAvailableAddedToMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202002052211519_NumberAvailableAddedToMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
